name: "Infra: Feature Testing: Init env"

on:
  workflow_dispatch:
  pull_request:
    types: ['labeled']

permissions:
  contents: read
  statuses: write

jobs:
  build:
    if: ${{ github.event.label.name == 'status/feature_testing' || github.event.label.name == 'status/feature_testing_public' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ github.token }}

      - name: get branch name
        id: extract_branch
        run: |
          tag='pr${{ github.event.pull_request.number }}'
          echo "tag=${tag}" >> $GITHUB_OUTPUT

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'maven'

      - name: Build Maven Project
        id: build
        run: |
          ./mvnw -B -ntp versions:set -DnewVersion=$GITHUB_SHA
          ./mvnw -B -V -ntp clean package -Pprod -DskipTests
          export VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: ./.github/workflows/build-docker
        with:
          tag: ${{ steps.extract_branch.outputs.tag }}
          version: ${{ steps.build.outputs.version }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          repository: 297478128798.dkr.ecr.eu-central-1.amazonaws.com/kafka-ui
          build-context: api

    outputs:
      tag: ${{ steps.extract_branch.outputs.tag }}

  make-branch-env:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: clone
        run: |
          git clone https://infra-tech:${{ secrets.INFRA_USER_ACCESS_TOKEN }}@github.com/kafbat/kafka-ui-infra.git --branch envs
      - name: create deployment
        run: |
          cd kafka-ui-infra/aws-infrastructure4eks/argocd/scripts
          echo "Branch:${{ needs.build.outputs.tag }}"
          ./kafka-ui-deployment-from-branch.sh ${{ needs.build.outputs.tag }} ${{ github.event.label.name }} ${{ secrets.FEATURE_TESTING_UI_PASSWORD }}
          git config --global user.email "infra@kafbat.io"
          git config --global user.name "infra-tech"
          git add ../kafka-ui-from-branch/
          git commit -m "added env:${{ needs.build.outputs.tag }}" && git push || true

      - name: update status check for private deployment
        if: ${{ github.event.label.name == 'status/feature_testing' }}
        uses: Sibz/github-status-action@v1.1.6
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "Click Details button to open custom deployment page"
          state: "success"
          sha: ${{ github.event.pull_request.head.sha || github.sha }}
          target_url: "http://${{ needs.build.outputs.tag }}.internal.ui.kafbat.dev"

      - name: update status check for public deployment
        if: ${{ github.event.label.name == 'status/feature_testing_public' }}
        uses: Sibz/github-status-action@v1.1.6
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "Click Details button to open custom deployment page"
          state: "success"
          sha: ${{ github.event.pull_request.head.sha || github.sha }}
          target_url: "http://${{ needs.build.outputs.tag }}.internal.ui.kafbat.dev"
