name: "Infra: Feature Testing Public: Init env"

on:
  workflow_dispatch:
    inputs:
      ENV_NAME:
        description: 'Will be used as subdomain in the public URL.'
        required: true
        default: 'demo'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ github.token }}

      - name: get branch name
        id: extract_branch
        run: |
          tag="${{ github.event.inputs.ENV_NAME }}-$(date '+%F-%H-%M-%S')"
          echo "tag=${tag}" >> $GITHUB_OUTPUT

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'maven'

      - name: Build Maven Project
        id: build
        run: |
          ./mvnw -B -ntp versions:set -DnewVersion=$GITHUB_SHA
          ./mvnw -B -V -ntp clean package -Pprod -DskipTests
          export VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build & Push Docker Image
        uses: ./.github/workflows/build-docker
        with:
          tag: ${{ steps.extract_branch.outputs.tag }}
          version: ${{ steps.build.outputs.version }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          repository: 297478128798.dkr.ecr.eu-central-1.amazonaws.com/kafka-ui
          build-context: api

    outputs:
      tag: ${{ steps.extract_branch.outputs.tag }}

  separate-env-create:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: clone
        run: |
          git clone https://infra-tech:${{ secrets.INFRA_USER_ACCESS_TOKEN }}@github.com/kafbat/ui-infra.git --branch envs

      - name: separate env create
        run: |
          cd kafka-ui-infra/aws-infrastructure4eks/argocd/scripts
          bash separate_env_create.sh ${{ github.event.inputs.ENV_NAME }} ${{ secrets.FEATURE_TESTING_UI_PASSWORD }} ${{ needs.build.outputs.tag }}
          git config --global user.email "infra@kafbat.io"
          git config --global user.name "infra-tech"
          git add -A
          git commit -m "separate env added: ${{ github.event.inputs.ENV_NAME }}" && git push || true

      - name: echo separate environment public link
        run: |
          echo "Please note, separate environment creation takes up to 5-10 minutes."
          echo "Separate environment will be available at http://${{ github.event.inputs.ENV_NAME }}.-ui.kafbat.io"
          echo "Username: admin"
