name: Print Env Vars

on:
  workflow_dispatch:

jobs:
  print-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment Variables
        run: |
          echo "ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}"
